# Generated by Django 6.0 on 2025-12-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('application_type', models.CharField(choices=[('member', 'Member'), ('volunteer', 'Volunteer')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('interview_datetime', models.DateTimeField(blank=True, null=True)),
                ('interview_link', models.URLField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
