# Generated by Django 6.0 on 2025-12-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='district',
        ),
    ]
