# Generated by Django 6.0 on 2025-12-09 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_district'),
        ('branches', '0003_remove_branch_districts_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
    ]
