# Generated by Django 6.0 on 2025-12-09 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_district_alter_application_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.AddField(
            model_name='application',
            name='citizenship_back',
            field=models.FileField(blank=True, null=True, upload_to='applications/citizenship/'),
        ),
        migrations.AddField(
            model_name='application',
            name='citizenship_front',
            field=models.FileField(blank=True, null=True, upload_to='applications/citizenship/'),
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hobbies_interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ideas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other_organizations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/photos/'),
        ),
        migrations.AddField(
            model_name='application',
            name='profession',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='self_definition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='social_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='temporary_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='time_commitment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='why_join',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
