# Generated by Django 6.0 on 2025-12-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_remove_application_address_remove_application_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(default='Nepal', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
