# Generated by Django 6.0 on 2025-12-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_country_alter_application_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_attended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
