# Generated by Django 6.0 on 2025-12-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_interview_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
