# Generated by Django 6.0 on 2025-12-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_application_khalti_payment_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejection_type',
            field=models.CharField(blank=True, choices=[('correction', 'Correction Required'), ('final', 'Final Rejection')], max_length=20, null=True),
        ),
    ]
