# Generated by Django 6.0 on 2025-12-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Aarambha Foundation', max_length=200)),
                ('subtitle', models.TextField(blank=True, default='Our Beginning for the Change')),
                ('background_image', models.ImageField(blank=True, help_text='Upload hero section background image. If not provided, default image will be used.', null=True, upload_to='hero_images/')),
                ('background_video', models.FileField(blank=True, help_text='Upload hero section background video (optional). Video takes precedence over image.', null=True, upload_to='hero_videos/')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to display this hero section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
                'ordering': ['-created_at'],
            },
        ),
    ]
