# Generated by Django 6.0 on 2025-12-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Card title', max_length=200)),
                ('description', models.TextField(help_text='Card description (supports HTML)')),
                ('image', models.ImageField(blank=True, help_text='Upload card image. If not provided, logo will be used.', null=True, upload_to='support_cards/')),
                ('button_text', models.CharField(default='Donate', help_text='Button text', max_length=50)),
                ('button_url', models.CharField(blank=True, help_text='Button URL (leave empty for default donate page)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to display this card')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support Card',
                'verbose_name_plural': 'Support Cards',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
