# Generated by Django 6.0 on 2025-12-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_supportcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload Who We Are section image. If not provided, default image will be used.', null=True, upload_to='who_we_are/')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to display this section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Who We Are Section',
                'verbose_name_plural': 'Who We Are Section',
                'ordering': ['-created_at'],
            },
        ),
    ]
