# Generated by Django 6.0 on 2025-12-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_whoweare'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingOurImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Growing Our Impact', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Upload Growing Our Impact section image. If not provided, default image will be used.', null=True, upload_to='growing_impact/')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to display this section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Growing Our Impact Section',
                'verbose_name_plural': 'Growing Our Impact Section',
                'ordering': ['-created_at'],
            },
        ),
    ]
