# Generated by Django 6.0 on 2025-12-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_growingourimpact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropouts_enrolled', models.PositiveIntegerField(default=29, help_text='Number of dropouts enrolled')),
                ('schools_supported', models.PositiveIntegerField(default=19, help_text='Number of schools supported')),
                ('projects', models.PositiveIntegerField(default=8, help_text='Number of projects')),
                ('districts', models.PositiveIntegerField(default=9, help_text='Number of districts')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to display this statistics section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistics Section',
                'verbose_name_plural': 'Statistics Section',
                'ordering': ['-created_at'],
            },
        ),
    ]
