# Generated by Django 6.0 on 2025-12-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(help_text='Event description')),
                ('image', models.ImageField(blank=True, help_text='Upload event image. If not provided, default image will be used.', null=True, upload_to='events/')),
                ('event_date', models.DateTimeField(blank=True, help_text='Event date and time (optional)', null=True)),
                ('location', models.CharField(blank=True, help_text='Event location (optional)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to display this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
