# Generated by Django 6.0 on 2025-12-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='Organization address')),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook URL (optional)')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram URL (optional)')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn URL (optional)')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube URL (optional)')),
                ('whatsapp_url', models.URLField(blank=True, help_text='WhatsApp URL (optional)')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to display this contact info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'ordering': ['-created_at'],
            },
        ),
    ]
