# Generated by Django 6.0 on 2025-12-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Award title', max_length=200)),
                ('image', models.ImageField(help_text='Upload award image', upload_to='awards/')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Award year (optional)', null=True)),
                ('description', models.TextField(blank=True, help_text='Award description (optional)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to display this award')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
