# Generated by Django 6.0 on 2025-12-12 15:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navlink', models.SlugField(help_text='Slug for URL and navbar link', unique=True)),
                ('title', models.CharField(help_text='Title of the work item', max_length=200)),
                ('description', ckeditor.fields.RichTextField(help_text='Rich text description with formatting and images')),
                ('main_image', models.ImageField(blank=True, help_text='Main image for the work item', null=True, upload_to='our_work/')),
                ('external_link', models.URLField(blank=True, help_text='Optional external link')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to display this work item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Our Work',
                'verbose_name_plural': 'Our Work',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
