# Generated by Django 6.0 on 2025-12-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ourwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDropoutReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(help_text='Name of the person reporting', max_length=200)),
                ('reporter_email', models.EmailField(help_text='Email of the reporter', max_length=254)),
                ('reporter_phone', models.CharField(blank=True, help_text='Phone number of the reporter', max_length=15)),
                ('dropout_name', models.CharField(help_text='Name of the school dropout', max_length=200)),
                ('dropout_age', models.PositiveIntegerField(help_text='Age of the dropout')),
                ('dropout_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender of the dropout', max_length=10)),
                ('school_name', models.CharField(help_text='Name of the school', max_length=200)),
                ('school_location', models.TextField(help_text='Location/address of the school')),
                ('district', models.CharField(help_text='District where the school is located', max_length=100)),
                ('reason_for_dropout', models.TextField(help_text='Reason for dropping out')),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional information')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Whether the report is anonymous')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('investigated', 'Investigated'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Dropout Report',
                'verbose_name_plural': 'School Dropout Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
