# Generated by Django 6.0 on 2025-12-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_schooldropoutreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], default='Mr.', max_length=10)),
                ('full_name', models.CharField(help_text='Full name of the donor', max_length=200)),
                ('email', models.EmailField(help_text='Email address of the donor', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the donor (optional)', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount in NPR', max_digits=10)),
                ('purchase_order_id', models.CharField(help_text='Unique purchase order ID', max_length=100, unique=True)),
                ('pidx', models.CharField(blank=True, help_text='Khalti payment identifier', max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Khalti transaction ID', max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'User Canceled'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('payment_url', models.URLField(blank=True, help_text='Khalti payment URL', null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Transaction fee', max_digits=10)),
                ('refunded', models.BooleanField(default=False, help_text='Whether the transaction has been refunded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the payment was completed', null=True)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
