from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views


urlpatterns = [
    path('', views.website_home, name='home'),
    path('api/our-work/', views.OurWorkAPI.as_view(), name='our_work_api'),
    path('member-form/', views.website_member_form, name='website_member_form'),
    path('volunteer-form/', views.website_volunteer_form, name='website_volunteer_form'),
    path('sponsor-child-form/', views.website_sponsor_child_form, name='website_sponsor_child_form'),
    path('get-involved/', views.get_involved, name='get_involved'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('guest/welcome/', views.guest_welcome, name='guest_welcome'),
    path('guest/dashboard/', views.guest_dashboard, name='guest_dashboard'),
    path('guest/profile/', views.guest_profile, name='guest_profile'),
    path('guest/applications/', views.guest_applications, name='guest_applications'),
    path('apply/member/', views.apply_member, name='apply_member'),
    path('apply/volunteer/', views.apply_volunteer, name='apply_volunteer'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/users/', views.admin_users, name='admin_users'),
    path('admin/branches/', views.admin_branches, name='admin_branches'),
    path('admin/applications/', views.admin_applications, name='admin_applications'),
    path('admin/tasks/', views.admin_tasks, name='admin_tasks'),
    path('admin/tasks/detail/', views.admin_task_detail, name='admin_task_detail'),
    path('admin/notices/', views.admin_notices, name='admin_notices'),
    path('admin/materials/', views.admin_materials, name='admin_materials'),
    path('member/notices/', views.member_notices, name='member_notices'),
    path('volunteer/notices/', views.volunteer_notices, name='volunteer_notices'),
    path('admin/core/herosection/', views.admin_herosection, name='admin_herosection'),
    path('admin/core/supportcards/', views.admin_supportcards, name='admin_supportcards'),
    path('admin/core/whoweare/', views.admin_whoweare, name='admin_whoweare'),
    path('admin/core/growingimpact/', views.admin_growingimpact, name='admin_growingimpact'),
    path('admin/core/statistics/', views.admin_statistics, name='admin_statistics'),
    path('admin/core/events/', views.admin_events, name='admin_events'),
    path('admin/core/partners/', views.admin_partners, name='admin_partners'),
    path('contact/', views.contact_us, name='contact_us'),
    path('admin/core/contact/', views.admin_contact, name='admin_contact'),
    path('admin/core/awards/', views.admin_awards, name='admin_awards'),
    path('admin/core/ourwork/', views.admin_ourwork, name='admin_ourwork'),
    path('our-work/<str:navlink>/', views.our_work_detail, name='our_work_detail'),
    path('report-school-dropout/', views.report_school_dropout, name='report_school_dropout'),
    path('admin/school-dropout-reports/', views.admin_school_dropout_reports, name='admin_school_dropout_reports'),
    path('member/dashboard/', views.member_dashboard, name='member_dashboard'),
    path('member/tasks/', views.member_tasks, name='member_tasks'),
    path('member/notifications/', views.member_notifications, name='member_notifications'),
    path('member/materials/', views.member_materials, name='member_materials'),
    path('dashboard/volunteer/', views.volunteer_dashboard, name='volunteer_dashboard'),
    path('volunteer/tasks/', views.volunteer_tasks, name='volunteer_tasks'),
    path('volunteer/materials/', views.volunteer_materials, name='volunteer_materials'),
    path('payment/success/<int:pk>/', views.payment_success, name='payment_success'),
    path('donation/callback/', views.donation_callback, name='donation_callback'),
    path('debug/auth/', views.debug_auth, name='debug_auth'),
]

