# Generated by Django 6.0 on 2025-12-09 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_district'),
        ('branches', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='districts',
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(default='TEMP', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.CharField(default='Not specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='branch',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
