# Generated by Django 6.0 on 2025-12-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_resubmitted', 'Application Resubmitted'), ('application_updated', 'Application Updated'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('interview_scheduled', 'Interview Scheduled'), ('interview_rescheduled', 'Interview Rescheduled'), ('general', 'General')], max_length=30),
        ),
    ]
